### ISSUE TITLE
Err(0xE) <- RT.GV wake failure

### ISSUE THREAD

**Issue by Hue-OwO** [Trijal08/OpenCore-Hackintosh-Lenovo-IdeaPad-3-15IIL05#2]
trying to boot into macOS sonoma installer, keep getting RT.GV wake failure error, i've tried booting into macOS ventura and still the same error

version: v1.0.1_r5
cpu: i3-1005g1

![IMG_4329](https://github.com/Trijal08/OpenCore-Hackintosh-Lenovo-IdeaPad-3-15IIL05/assets/71944049/b61ed8da-5831-472f-80e0-bf6c7b7d107d)

**Comment by Trijal08** [comment]
> trying to boot into macOS sonoma installer, keep getting RT.GV wake failure error, i've tried booting into macOS ventura and still the same error
> 
> version: v1.0.1_r5 cpu: i3-1005g1
> 
> ![IMG_4329](https://private-user-images.githubusercontent.com/71944049/341840887-b61ed8da-5831-472f-80e0-bf6c7b7d107d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNjM0NDAsIm5iZiI6MTcxOTE2MzE0MCwicGF0aCI6Ii83MTk0NDA0OS8zNDE4NDA4ODctYjYxZWQ4ZGEtNTgzMS00NzJmLTgwZTAtYmY2YzdiN2QxMDdkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDE3MTkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4NzJmMDNiZGQyNTMwMTdkYmQ2MzIwOGVhYTMzOGZhYzM5YjY2YTZmZTY1NjI0NDJmYzMyMzU2NzI4MDRmODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9iNczjWFX5awHAje3MnaOhIRoPVuKtgTZe3LbZkS9Ww)

Make sure your BIOS settings are alright: SATA Mode should be configured to AHCI and Secure Boot should be disabled and the Boot Mode should be UEFI Only. Even if that does not work; try this [EFI](https://github.com/Trijal08/OpenCore-Hackintosh-Lenovo-IdeaPad-3-15IIL05/archive/refs/heads/main.zip) and tell me how it goes! 

P.S.: Sorry for the late reply! Actually, I just got a new ThinkPad T490; so I am trying to hackintosh that!

**Comment by Hue-OwO** [comment]
got it working fine, just made my own efi and copied a few things from yours, spoofed igpu and some ssdt’s, just need to get the trackpad working
![IMG_4388](https://github.com/Trijal08/OpenCore-Hackintosh-Lenovo-IdeaPad-3-15IIL05/assets/71944049/b5900af2-0dd9-4c86-856b-a1bb72025441)

**Comment by Trijal08** [comment]
> got it working fine, just made my own efi and copied a few things from yours, spoofed igpu and some ssdt’s, just need to get the trackpad working
> ![IMG_4388](https://github.com/Trijal08/OpenCore-Hackintosh-Lenovo-IdeaPad-3-15IIL05/assets/71944049/b5900af2-0dd9-4c86-856b-a1bb72025441)
> 

Send me your config.plist; please! Anyway, can you please try my EFI again from the same link and tell me how to goes? Make sure to also keep a copy of your current EFI.
